# Exercise: Geographical Cluster Analysis of Taxi Rides
Using the NY Taxi data set (see Use Case Block I) and the use case from the lecture...

In [1]:
import pandas as pd
import numpy as np
import folium


In [2]:
# we load the data we have saved after wrangling and pre-processing in block I
train=pd.read_csv('../../DATA/train_cleaned.csv')

In [3]:
#select only the culumns with the ride coordinates
coordinates = train[ ['pickup_latitude','pickup_longitude','dropoff_latitude' , 'dropoff_longitude' ] ]

## Clustering approach from the lecture
we will be using simple K-Means:
https://scikit-learn.org/stable/modules/generated/sklearn.cluster.KMeans.html

In [4]:
from sklearn.cluster import KMeans

In [5]:
#define number of clusters and create instance
clusters=100
myKMeans=KMeans(n_clusters=clusters, n_jobs=-1)#parallelize to all cores

In [6]:
%%time
#train model
myKMeans.fit(coordinates.to_numpy()[:100000,:])#use only subset of the data to make it faster

Wall time: 2min


KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
       n_clusters=100, n_init=10, n_jobs=-1, precompute_distances='auto',
       random_state=None, tol=0.0001, verbose=0)

In [7]:
#get cluster centers
centers=myKMeans.cluster_centers_
print(centers)

[[ 40.76882298 -73.98343434  40.75907209 -73.97560211]
 [ 40.6467225  -73.78544051  40.75480626 -73.98299499]
 [ 40.75456985 -73.92762237  40.75652496 -73.93490123]
 [ 41.366138   -73.137393    41.366138   -73.137393  ]
 [ 40.72709324 -73.9918563   40.74504514 -73.98533363]
 [ 40.78362802 -73.97634002  40.77626099 -73.95604575]
 [ 40.71642208 -73.84512016  40.71640363 -73.8377228 ]
 [ 41.366138   -73.137393    40.7498045  -73.9601465 ]
 [ 40.75174019 -73.97924491  40.72291946 -73.82997823]
 [ 40.73988693 -73.99318721  40.78670103 -73.97540672]
 [ 40.77260119 -73.95388781  40.74102245 -73.9896525 ]
 [ 40.71035821 -73.95331829  40.68033683 -73.97459743]
 [ 40.72178545 -73.99770351  40.76627094 -73.86941413]
 [ 40.72812603 -73.99141354  40.73598554 -74.00252577]
 [ 40.72976707 -73.99512131  40.6472437  -73.78594411]
 [ 40.77139708 -73.8704798   40.77893609 -73.95902987]
 [ 40.78593554 -73.97582906  40.768639   -73.9817389 ]
 [ 40.66544889 -73.77864048  40.73059603 -73.75915758]
 [ 40.7275

In [8]:
#draw map: green: start, red: end
cluster_map = folium.Map(location = [40.730610,-73.935242],zoom_start = 12,)
for i in range(clusters):
    folium.CircleMarker([centers[i,0], centers[i,1]], radius=3,                
                        color="green", 
                        fill_opacity=0.9
                       ).add_to(cluster_map)
    folium.CircleMarker([centers[i,2], centers[i,3]], radius=3,                
                        color="red", 
                        fill_opacity=0.9
                       ).add_to(cluster_map)
    folium.PolyLine([ [centers[i,0],centers[i,1]] , [centers[i,2],centers[i,3]]  ], color="black", weight=2.5, opacity=1).add_to(cluster_map)

In [9]:
cluster_map

## Exercise 1
Write a function ```show_cluster(cluster_number,...)``` that draws the cluster centers and all start and end points of a given cluster in the map.
* use the ```predict()``` method to map all data in ```train_data``` to a cluster center
* use ```folium.CircleMarker``` to draw all members of a given cluster


In [ ]:
def show_cluster(cluster_number, ):
    

## Exercise 2
Write a function ```cluster_var(cluster_number,...)``` that computes the intra- and extra cluster variance for a given cluster. Apply it to all clusters and compare the results for k=100 and k=10.